exclude: 'node_modules|.git'
default_stages: [pre-commit]
fail_fast: false


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: "api_next.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        name: "Run ruff import sorter"
        args: ["--select=I", "--fix"]

      - id: ruff
        name: "Run ruff linter"

      - id: ruff-format
        name: "Run ruff formatter"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss]
        # Ignore any files that might contain jinja / bundles
        exclude: |
            (?x)^(
                api_next/public/dist/.*|
                .*node_modules.*|
                .*boilerplate.*|
                api_next/templates/includes/.*|
                api_next/public/js/lib/.*
            )$


  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        types_or: [javascript]
        args: ['--quiet']
        # Ignore any files that might contain jinja / bundles
        exclude: |
            (?x)^(
                api_next/public/dist/.*|
                cypress/.*|
                .*node_modules.*|
                .*boilerplate.*|
                api_next/templates/includes/.*|
                api_next/public/js/lib/.*
            )$

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
        exclude: ^api_next/tests/

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: false
        args: ["-x", "api_next/tests/", "--tb=short"]
        stages: [pre-push]

      - id: test-coverage-check
        name: test-coverage-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: false
        args: ["--cov=api_next", "--cov-fail-under=80", "--tb=short"]
        stages: [pre-push]

ci:
    autoupdate_schedule: weekly
    skip: [pytest-check, test-coverage-check]
    submodules: false
